---
- name: Add Grafana APT repository (Debian/Ubuntu)
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
  when: ansible_os_family == "Debian"
  tags: [configure, grafana]

- name: Add Grafana GPG key (Debian/Ubuntu)
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  when: ansible_os_family == "Debian"
  tags: [configure, grafana]

- name: Install Grafana (Debian/Ubuntu)
  apt:
    name: grafana
    state: present
  when: ansible_os_family == "Debian" and (monitoring.install_grafana | default(true))
  tags: [install, grafana]

- name: Install Grafana (CentOS/RHEL)
  yum:
    name: grafana
    state: present
  when: ansible_os_family == "RedHat" and (monitoring.install_grafana | default(true))
  tags: [install, grafana]

- name: Ensure Grafana running
  service:
    name: grafana-server
    state: started
    enabled: true
  when: monitoring.install_grafana | default(true)
  tags: [service, grafana]
